name: "🌀 » Release '🗿• Tuya +' integration"

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ZIP Component Dir
        run: |
          cd ${{ github.workspace }}/custom_components/localtuya
          zip -r ha_tuya.zip ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/localtuya/ha_tuya.zip
          asset_name: ha_tuya.zip
          tag: ${{ github.ref }}
          overwrite: true
